name: rasedi_flutter_sdk
description: A new Flutter package for Rasedi Payment Gateway.
version: 1.0.0
homepage: https://github.com/MirotechTeam/rasedi-flutter-sdk

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  basic_utils: ^5.5.4
  pointycastle: ^3.7.3
  cryptography: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

false_secrets:
  - example/example.dart
